uploads = []
outputs = []

[[generated]]
id = "YlEjaJha0rdFjd9ozMkba"
uri = "file://artifacts/clippzi/src/assets/logo.png"
type = "image"
title = "Clippzi flame logo"

[[generated]]
id = "kN75H_tu4auwshJ15VIiK"
uri = "file://artifacts/clippzi/src/assets/avatar1.png"
type = "image"
title = "Diverse creator avatar 1"

[[generated]]
id = "2vp4N60gJz9jtTiJWY9pO"
uri = "file://artifacts/clippzi/src/assets/avatar2.png"
type = "image"
title = "Diverse creator avatar 2"

[[generated]]
id = "OLTLMfNyVVTz0XQlHvSwx"
uri = "file://artifacts/clippzi/src/assets/avatar3.png"
type = "image"
title = "Diverse creator avatar 3"

[[generated]]
id = "fFdGzAKTVUzgljzkwTd8_"
uri = "file://artifacts/clippzi/public/gifts/thors-hammer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "czvQonJdFEOH40yd41_OB"
uri = "file://artifacts/clippzi/public/gifts/gorilla-vs-trex.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gKY-7Mq16wJRVVX2zsNB9"
uri = "file://artifacts/clippzi/public/gifts/dragon-strike.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pnbIoXlN9uoFMIPrrrrz3"
uri = "file://artifacts/clippzi/public/gifts/phoenix-rebirth.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VVutawQhW7A_pmZ0WUXmf"
uri = "file://artifacts/clippzi/public/gifts/lambo-drop.png"
type = "image"
title = "generated_image"

[[generated]]
id = "EzbRXp0rxppg_gMi1U6wO"
uri = "file://artifacts/clippzi/public/gifts/stack-of-cash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "-A8s-8wFnIjOb2qM-IZJG"
uri = "file://artifacts/clippzi/public/gifts/king-crown.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XqIMeD5UJb7pv-ZAbqQvs"
uri = "file://artifacts/clippzi/public/gifts/treasure-chest.png"
type = "image"
title = "generated_image"

[[generated]]
id = "g_RNNRP3NN9vvovx8bZO5"
uri = "file://artifacts/clippzi/public/gifts/clippzi-diamond.png"
type = "image"
title = "generated_image"

[[generated]]
id = "F-Aw-95c_oKQvTo5-849o"
uri = "file://artifacts/clippzi/public/gifts/galactic-throne.png"
type = "image"
title = "generated_image"

[[generated]]
id = "d-oW_JMyh8iWJtRaRA8eN"
uri = "file://artifacts/clippzi/public/gifts/clippzi-legend.png"
type = "image"
title = "generated_image"

[[generated]]
id = "98grD-v_iODWGraRjQwgP"
uri = "file://artifacts/clippzi/public/gifts/universe.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rgG1k7LTNCcxnIS5kkSOu"
uri = "file://artifacts/clippzi/public/gifts/private-jet.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PJLQyPUZ70owetsEqU1d6"
uri = "file://artifacts/clippzi/public/gifts/god-mode.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sQ2Lvc8K6r5zVPuwqkeoE"
uri = "file://artifacts/clippzi/public/gifts/titan.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tY4kjfamGhvenHlVfBUIL"
uri = "file://artifacts/clippzi/public/gifts/cyber-dragon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7pkyn3Z260ECLzY6jvoO-"
uri = "file://artifacts/clippzi/public/gifts/galaxy-brain.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QEtWNKXAz2W4R81HuUgE5"
uri = "file://artifacts/clippzi/public/gifts/queens-tiara.png"
type = "image"
title = "generated_image"

[[generated]]
id = "AoCG2ANRdizjkm14nir5H"
uri = "file://artifacts/clippzi/public/gifts/nuclear-star.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uzYYI4szkIR547ElQcd2Q"
uri = "file://artifacts/clippzi/public/gifts/clippzi-king.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mL_xqlGp335wvx6X2n3JK"
uri = "file://artifacts/clippzi/public/gifts/golden-crown.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RHG5ly8HYtBJOKjrb_taz"
uri = "file://artifacts/clippzi/public/gifts/excalibur.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9fNnw45OEsyP7l5MkrImk"
uri = "file://artifacts/clippzi/public/gifts/mega-yacht.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SnAdwajln__zQB4pv0tb1"
uri = "file://artifacts/clippzi/public/gifts/spartan-warlord.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZFqJBPxLJHNPopr14kqe2"
uri = "file://artifacts/clippzi/public/gifts/pharaohs-sarcophagus.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8siWXAWa8BgK_5FSpmC3V"
uri = "file://artifacts/clippzi/public/gifts/space-station.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gPJkPU_06lmSVPLrjHrsN"
uri = "file://artifacts/clippzi/public/gifts/island.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xV3ZPsgnQ1oLMgQ_U3l3E"
uri = "file://artifacts/clippzi/public/gifts/crypto-moon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4JFi8M4_noEhHw9_udXvo"
uri = "file://artifacts/clippzi/public/gifts/sports-legend.png"
type = "image"
title = "generated_image"
